server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer #Eureka服务注册名
  cloud:
      stream:
        binders: # 在此处配置要绑定的rabbitmq的服务信息；
          defaultRabbit: # 表示定义的名称，用于于binding整合
            type: rabbit # 消息组件类型
            environment: # 设置rabbitmq的相关的环境配置
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
        bindings: # 服务的整合处理
          input: # 这个名字是一个通道的名称
            destination: studyExchange # 表示要使用的Exchange名称定义
            content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
            binder: defaultRabbit # 设置要绑定的消息服务的具体设置
            #消费分组，注意：若未设置分组会有如下问题
            #1.重复消费问题，不同组是可以都去消费消息（重复消费）的，相同组才相互竞争只有一个去消费消息
            #2.持久化问题,当该服务未恢复时且这过程中生产方生产了新消息，就算服务重新启动恢复也不会去消费过去未消费的消息（类似丢失消息）
            group: msg_a

#客户端进行Eureka注册的配置
eureka:
  client: 
    service-url:
      register-with-eureka: true
      fetch-registry: true
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #在信息列表时显示主机名称
    instance-id: stream-consumer8803
    #鼠标悬浮链接显示实例的名称
    hostname: stream-consumer    
    #访问的路径变为IP地址,若为false:则鼠标悬浮显示实例的hostname配置，true:则优先显示Ip   
    prefer-ip-address: true    
    #设置心跳的时间间隔（默认是30秒）      
    lease-renewal-interval-in-seconds: 2
    #如果现在超过了5秒的间隔（默认是90秒）
    lease-expiration-duration-in-seconds: 5

#日志
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/stream-consumer8803.log
  #日志文件最大xxMB
  maxSize: 30MB 
  #保存xx天的日志
  maxHistory: 20
  #日志文件所在储存空间最大xxGB
  totalSizeCap: 10GB


